### ISSUE TITLE
[SL-1633] [Feature] Support metric/measure filters

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#1018]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

# **Context**

Some metrics require multiple aggregations or dependencies on other metrics. For example, a company might measure “super users” which is calculated as a distinct count of users who have 10+ active days in the last 70 days. Another metric might measures “activated spaces” which is calculated as a distinct count of spaces where at least two users have two active days within the first 7 days of space creation.  Both of these metrics require dependencies on some aggregation in order to produce the end metric and our framework has no path to supporting this today. This paradigm is sometimes called “metrics as dimensions” by our users where an aggregation is an input to the metric definition. 

# Proposed Solution

We could refer to metrics and measures in ***metric definitions*** or in queries in the same way that we currently reference dimensions. For example, I could ask for `user__bookings`  or `listing__bookings` where `bookings` is a metric. 

We’re proposing only allowing references to metrics or measures in metric definitions rather than measure definitions to preserve measures as only defining the aggregation while metrics define the function for how measures are used. 

## Benefits

This enables a few interesting benefits:

- Reference explicitly measures or metrics aggregated to a specific entity in other metrics
    
    ```sql
    semantic_models:
    	- name: users
    		entities:
    			- name: user
    				type: primary
    			- name: market
    				type: foreign
    		measures: 
    			- name: users
    				expr: user_id
    				agg: count_distinct
    		dimensions:
    			- name: is_host
    				type: categorical
    			- name: ds
    				type: time
    	- name: bookings
    		entities: 
    			- name: booking
    				expr: primary
    			- name: user
    				type: foreign
    		dimensions
    			- name: is_instant
    				type: categorical
    		measures: 
    			- name: bookings
    				expr: 1
    				agg: sum
    	- name: markets
    		entities:
    			- name: market
    				type: primary
    		measures: 
    			- name: markets
    				expr: market_id
    				agg: count
    
    metrics:
      - name: active_users
    		type: simple
    		type_params:
    			measure: users
    		constraint:|
    				{{Measure('user__bookings')}} > 2 -- Reference to a measure aggregated to an entity level. Requires a primary to foreign join. 
    	- name: active_markets
    		type: simple
    		type_params:
    			measure: markets
    		constraint:|
    			{{Dimension('market__type')}} = 'Expansion' AND
    			{{Dimension('market__is_active'}} AND
    			{{Metric('market__active_users')}} > 100 -- reference to a metric. Requires a primary to foreign join. This metric also has a dependency on user_bookings through active_users 
    			  
    ```
    
- Reference metrics and measures aggregated to a specific entity level through the framework as a filter.

```sql
-- filter for users with more than two bookings
mql query --metrics users --dimensions ds, is_host  --where {{Measure('user__bookings')}} > 2
```

```sql
select 
		count(user_id) as users
	, ds
	, is_host
from
(
select 
		count(*) as bookings
	, user_id
from 
	users 
join 
	bookings on users.user_id = bookings.user_id
group by 
	2
having 
	bookings > 2
)
group by 1,2
```

### Query Examples

- Querying `active_users`
    - `mf query --metrics active_users --group-by is_host, ds --explain`

```sql
select
		count(distinct user_id) as active users
	, is_host,
	, ds
from users --users is primary on the right and foreign on the left, but there is no fanout because we aggregate to the user entity
inner join ( -- inner join users with more than two bookings
	select
		 users_id
		, sum(1) as bookings
	from 
		bookings
	group 
		by 1
	having 
		bookings >2
) bookings on users.user_id = bookings.user_id
```

### Describe alternatives you've considered

The alternative is to pre-aggregate these metrics in your semantic model downstream of the semantic layer. 

<sub>[SL-1633](https://linear.app/dbt-labs/issue/SL-1633/[feature]-support-2-step-aggregations)</sub>

**Comment by Scared-Heart** [comment]
Hi, this is an excellent feature, but I see it's been marked as 'not planned.' Will there be any future support for this?
