### ISSUE TITLE
[Feature] Leverage other python lib to generate sql code instead of hand-crafting all platform-specific code

### ISSUE THREAD

**Issue by chulucninh09** [dbt-labs/metricflow#1114]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hi, currently we have to implement SQL code render for every platform. Can we use other python lib such as `sqlglot` to have generic code that can generate code more programtically? Another perk is we can immediately have 20+ dialec supported.

### Describe alternatives you've considered

Implement per-platform code, which is labor-costing and easy to break, hard to maintain when interfaces change

### Who will this benefit?

Data Engineer, Data Analyst who just want to deliver their application and quickly adapt to other platform

### Are you interested in contributing this feature?

Yes

**Comment by Jstein77** [comment]
I created a discussion for this here: https://github.com/dbt-labs/metricflow/discussions/1219
