### ISSUE TITLE
[SL-2418] [Bug] Missing column names when writing a query to CSV

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#1285]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run `mf query --metrics revenue --group-by metric_time__week  --csv test` the csv result does not include the metric or dimension names. 

The first for rows for test.csv are:
```
2016-09-26 00:00:00,4221.0
2016-10-31 00:00:00,4880.0
2016-11-14 00:00:00,6020.0
2016-11-21 00:00:00,6530.0
```

### Expected Behavior

I expect the first row of the CSV to be the metrics and dimensions in my query

```
metric_time__week, revenue
2016-09-26 00:00:00,4221.0
2016-10-31 00:00:00,4880.0
2016-11-14 00:00:00,6020.0
2016-11-21 00:00:00,6530.0
```

### Steps To Reproduce

1. In dbt 1.8 and mf version 0.7.0 run `mf query --metrics revenue_offset --group-by metric_time__week  --csv test`
2. The CSV will not inlcude the metric and dimension names in the first row.

### Environment

```markdown
- OS:
- Python:
- dbt:
- metricflow:
```

<sub>[SL-2418](https://linear.app/dbt-labs/issue/SL-2418/[bug]-missing-column-names-when-writing-query-re)</sub>

**Comment by saurabh0402** [comment]
Hey @Jstein77, we are facing some issues because of this. Would it be fine if I pick this up?
