### ISSUE TITLE
Support Trino

### ISSUE THREAD

**Issue by nhandel** [dbt-labs/metricflow#207]
Describe the Feature
MetricFlow should be able to issue queries against Trino. This requires:

Adding a Trino SqlClient (with its associated attributes struct),
(If necessary) updating the SQL rendering to handle any dialect-specific syntaxes
Ensuring the test suite passes against a Trino target warehouse

Would you like to contribute?
This is a great first issue!

Anything Else?

**Comment by tlento** [comment]
Note: Trino has a formally supported SQLAlchemy library in their python client package: https://github.com/trinodb/trino-python-client
