### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#277]
**Describe the bug**
Metricflow is pinned to Python versions `>=3.8` and `< 3.10`. The latter constraint is in place because one or more of our package dependencies has a dependency on a custom backwards-compatibility library for managing the Python 2.7 -> Python 3 transition. This package triggers a "from collections import <some_abstract_class>" statement under the Python 2.7 condition, which is almost certainly caused by the way Python's import logic works with top level statements. That statement needs to be replaced with "from collections.abc import <some_abstract_class>", which is enforced in Python 3.10, but it can't just be updated or removed because under 2.7 the collections.abc package doesn't exist.

The main source of these errors is the `moz_parse` dependency, but there may be others.

To solve the issue with moz_parse we either need to:

1. Fix the import behavior of the compatibility shim in the upstream project
2. Update the upstream project to stop using the compatibility shim, since 2.7 hasn't been supported in ages
3. Change our SQL parser out for something else

We also need to fix any other packages with 3.10 compatibility problems.

Note - the moz-parse dependency we use is extremely old - the project split deployments, so updating to the latest mo-sql-parsing might just fix the issue. If it does not, we'll need to make that update in order to push changes to upstream.

**Steps To Reproduce**

1. Install Metricflow in a Python 3.10 environment
2. Try to run `mf query`

**Comment by tlento** [comment]
We use this: https://pypi.org/project/moz-sql-parser/

We should probably use this: https://pypi.org/project/mo-sql-parsing/

**Comment by tlento** [comment]
Update:

Upgrading to mo-sql-parsing likely solves the runtime failures.

Unfortunately, we cannot build metricflow under Python 3.10 because:

1. The version of the Databricks SQL connector we depend on requires `pyarrow 5.x.x`
2. pyarrow has a flawed dependency configuration that was fixed in `pyarrow 6.0`
3. The Google BigQuery SQLAlchemy package does not support `pyarrow > 7`
4. The next update to Databricks requires `pyarrow 9.x.x`

This is unresolvable as-is. The options now are:

1. Stop using the BigQuery SQLAlchemy package and cut over to the main BigQuery python connector, which supports PyArrow up to version 11, then update databricks and etc.
2. Fork the metricflow package into warehouse-specific packages and a `core` package such that BigQuery and Databricks can happily have their own separate dependency requirements so long as the `core` package works with everything
3. Push for these other projects to ship updates to these dependency versions and then update here when we have resolution. If BigQuery's SQLAlchemy package will accept later PyArrow versions that solves this particular problem.

Option 2 is the most robust, but it's also the most work.

**Comment by lorr1** [comment]
Any update on this? Am using python 3.10 and want to start to switch to using metricflow versus dbt metrics.

**Comment by Jstein77** [comment]
@lorr1 Python 3.10 is now supported!
