### ISSUE TITLE
bump tabulate dependency

### ISSUE THREAD

**Issue by vviers** [dbt-labs/metricflow#397]
Hey there !

It appears that metricflow requires `tabulate==0.8.9` in order to install it, however this makes it incompatible with a few other data science library, including the very popular [frictionless](https://github.com/frictionlessdata/framework) data framework which requires `tabulate>=0.8.10`

Any reasons not to loosen the tabulate requirement to something like `tabulate>=0.8.9`

Many thanks for the great work :)

**Comment by tlento** [comment]
Hi @vviers  - sorry, I missed this issue altogether!

We have an internal downstream dependency pinned to that. Let me see if I can relax that pin, and if it all works we can certainly update here.

**Comment by tlento** [comment]
It appears we don't use this library directly in Metricflow anymore (if we ever did), so it may be safe to simply remove the dependency from our list.

I'm working on a PR stack to clean up a bunch of type errors, and that has uncovered some other vestigial dependencies, so hopefully we can get this done for our next release.

**Comment by waligob** [comment]
Bumping this given the recent release of `dbt-metricflow (0.1.0)`, as `data-diff (0.7.13)` and `dbt-metricflow (0.1.0)` have incompatible dependencies. See below for the results of `poetry lock`:

```sh
$ poetry lock
Updating dependencies
Resolving dependencies... (1.7s)

Because dbt-metricflow (0.1.0) depends on metricflow (>=0.200.0,<0.201.0)
 and no versions of metricflow match >0.200.0,<0.201.0, dbt-metricflow (0.1.0) requires metricflow (0.200.0).
And because metricflow (0.200.0) depends on tabulate (>=0.8.9,<0.9.0)
 and data-diff (0.7.13) depends on tabulate (>=0.9.0,<0.10.0), dbt-metricflow (0.1.0) is incompatible with data-diff (0.7.13).
So, because inquirer-dbt depends on both data-diff (0.7.13) and dbt-metricflow (0.1.0), version solving failed.
```

**Comment by tlento** [comment]
We only use this in our dev builds but when I tried to sequester it last time some random Pandas thing stopped working.

I would dearly love to eliminate all of our Pandas dependencies, which would solve a bunch of similar problems for us, but I can't get that done any time soon.

Anyway, let me try some things and I'll get back to this in a bit.
