### ISSUE TITLE
Support for dbt v1.4.0

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/metricflow#416]
**Describe the Feature**
dbt-core v1.4.0 released this week and made some changes under the hood around classes/constructs that are referenced in MetricFlow's dbt integration. 

### What changed that is relevant to MetricFlow
**Consolidating Classes:**
Previously, dbt had the concept of Parsed & Compiled nodes that had significiant overlap in the codebase. We cleaned this up under the hood and combined them into a single construct just called Nodes. Why is this relevant? In the `dbt_to_metricflow` [file](https://github.com/transform-data/metricflow/blob/d5dd7e916adf7d1865cf820d9357c8440721b287/metricflow/model/transformations/dbt_to_metricflow.py#L6) on line 6 you import `ParsedMetric` and `ParsedModelNode` - these have been renamed to `Metric` and `Model` respectively and now come from [this file.](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/graph/nodes.py)

**Metrics & Timestamps**
We made the `timestamp` property in a dbt metric an optional input. This [line](https://github.com/transform-data/metricflow/blob/d5dd7e916adf7d1865cf820d9357c8440721b287/metricflow/model/transformations/dbt_to_metricflow.py#L158) appears to define the timestamp so it would just add an empty string. Pretty sure that doesn't break anything (including the filter logic a[ few lines down](https://github.com/transform-data/metricflow/blob/d5dd7e916adf7d1865cf820d9357c8440721b287/metricflow/model/transformations/dbt_to_metricflow.py#L167)) but wanted to flag.

**Anything Else?**
I think those are the only ones that we'd want to call out!

**Comment by callum-mcdata** [comment]
@QMalcolm not sure if this is a new issue or part of this one but I noticed something when testing out the new `derived` functionality. There was an issue where one of the component metrics was returning NULL (issue with the base dataset that I've since resolved) and that was causing the derived metric to return NULL instead of the other values. In the below example, `net_profit` is equal to `revenue - (costs + taxes)`

<img width="500" alt="image" src="https://user-images.githubusercontent.com/101437052/215144678-8eb6ba6c-3e59-4c5b-bcc7-7115531178e8.png">

Now, this could be intentional as I know that we've run into issues with this same problem. The reason that I bring it up is because we have a config property called `treat_nulls_as_zero` that coalesce's those null values to 0 for the purposes of the derived metrics. It can be found in the metric object under config (which is a permissive property that includes anything listed in the input - we validate in the metrics package and not dbt-core unfortunately).

 I did a quick cmd+k against `metricflow` and noticed that property didn't appear in `dbtConverter` so figured I'd 🎏 .

**Comment by QMalcolm** [comment]
@callum-mcdata Nice catch! I really appreciate this type of digging in 🙂 I think I know how to resolve the `treat_nulls_as_zero` issue. Basically our measures (which is how we treat component metrics) can be defined via an expression. I should be able to detect when `treat_nulls_as_zero` is set, and use this to determine how the MF measure is configured.

**Comment by QMalcolm** [comment]
Also for transparency on the main issue, support for dbt 1.4.0, @callum-mcdata and I talked via slack. We're working on it 🎉 First we're going to tie up some loose ends by refactoring [dbt_to_metricflow.py](https://github.com/transform-data/metricflow/blob/main/metricflow/model/transformations/dbt_to_metricflow.py) to use the [DbtConverter](https://github.com/transform-data/metricflow/blob/main/metricflow/model/dbt_converter.py#L71) so that we have closer to a singular implementation of how dbt projects can become MetricFlow models. Then we'll update support for dbt `1.4.0` and both dbt cloud and dbt core will get the improvements easily.
