### ISSUE TITLE
Whether only query dimensions are supported?

### ISSUE THREAD

**Issue by lexluo09** [dbt-labs/metricflow#429]
**Describe the Feature**
Whether only query dimensions are supported ?
In some case,I want to query dimensions and not specifying metrics. Is this situation supported？

**Comment by tlento** [comment]
At this time we do not support queries against dimensions without any metrics specified, although we do support querying for the distinct values of a given dimension associated with a metric. This has been requested in the past.

Would you mind sharing more details about your use case here so we can see how it fits in with other features we've been discussing in this area?

**Comment by Jstein77** [comment]
I'm going to close this out as the initial question was answered. @lexluo09 if you could share details on your use case that would be really helpful!
