### ISSUE TITLE
dbt_repo not used by validate-configs

### ISSUE THREAD

**Issue by JacobBush** [dbt-labs/metricflow#434]
**Describe the bug**
`mf validate-configs` does not respect the `dbt_repo` configuration parameter.

**Steps To Reproduce**
`./metricflow/config.yml`
```yaml
dbt_repo: 'true'  # MetricFlow only parses this correctly if its a string...
model_path: dbt  # Parse the DBT configuration file
```

In addition, the `./dbt` directory exists and is a valid DBT project.

```
➜  MF_CONFIG_DIR=metricflow mf validate-configs
(To see warnings and future-errors, run again with flag `--show-all`)
✔ 🎉 Successfully linted config YAML files (ERRORS: 0, FUTURE_ERRORS: 0, WARNINGS: 0)
✖ Breaking issues found when building model from configs (ERRORS: 57, FUTURE_ERRORS: 0, WARNINGS: 0)
• ERROR: in file `dbt/models/sources/snapshot/channels.yml` on line #1 - Document should have one type of key, but has dict_keys(['version', 'sources']).
... (repetitive errors omitted for brevity)
```

**Expected behavior**
I expect that the DBT project will be parsed appropriately.

**Potential Solution**
Hypothesis: MetricFlow is not parsing this as a DBT repository, but instead as a folder of "regular" MetricFlow configs.

I know that MF can parse the project, because I can do it with python directly
```
➜ python -c "from metricflow.model.parsing.dbt_dir_to_model import get_dbt_config; print(get_dbt_config('dbt'));"
... (omitted for brevity)
```

After a bit of investigation, it seems like the CLI does not respect the `dbt_repo` parameter.
This can be fixed with a 2-line addition to [`metricflow/cli/main.py` on line 802](https://github.com/transform-data/metricflow/blob/main/metricflow/cli/main.py#L802):
```py
    elif cfg.model_path_is_for_dbt:
        parsing_result = model_build_result_from_dbt_config(handler=cfg.config, raise_issues_as_exceptions=False)
```
and an update to the import on line `54` to also include `model_build_result_from_dbt_config`.

Doing this gives the expected behaviour
```
➜ MF_CONFIG_DIR=metricflow mf validate-configs                                                                  
(To see warnings and future-errors, run again with flag `--show-all`)
✔ 🎉 Successfully linted config YAML files (ERRORS: 0, FUTURE_ERRORS: 0, WARNINGS: 0)
... (A bunch of unrelated DBT warnings)
✔ 🎉 Successfully built model from configs (ERRORS: 0, FUTURE_ERRORS: 0, WARNINGS: 0)
✔ 🎉 Successfully validated the semantics of built model (ERRORS: 0, FUTURE_ERRORS: 0, WARNINGS: 0)
```

**Environment (please complete the following information):**
- MetricFlow Version = 0.140.0

**Comment by Jstein77** [comment]
This issue uses the old spec and is not relevant anymore. `mf validate-configs` will run validations on the root directory.
