### ISSUE TITLE
Remove Materializations

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/metricflow#442]
### **The Feature**
As part of the integration with `dbt-core`, we will be removing `materializations` from MetricFlow. The functionality will most likely exist in some other form but it won't be `materializations`. 

**Would you like to contribute?**
Absolutely. Happy to take this on as a first commit to MetricFlow and additionally a first pass at the stacked diffs method of commits.

**Comment by mazinesy** [comment]
:wave: Will this be a name change ? Or is it deeper than that ?

**Comment by polmonso** [comment]
How do we materialize metrics in dbt 1.6-1.7 ? Did you ever find an answer @mazinesy ?
