### ISSUE TITLE
Create a `metric_formula` property of Metric

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/metricflow#469]
**Describe the Feature**
This property would contain the "formula" that creates a metric. For most metrics this would be the `expression` but for `ratio` metrics it will require us to create it with num/denom.

**Would you like to contribute?**
@QMalcolm probably has the most context here for how to implement this one.

**Comment by QMalcolm** [comment]
I think we ended up deciding against `metric_formula`, I could be wrong though. If this is still relevant we should move this issue to dbt-semantic-interfaces
