### ISSUE TITLE
[Feature]  When will the (0.150.0  or  0.200.0 ) version be released 

### ISSUE THREAD

**Issue by lexluo09** [dbt-labs/metricflow#557]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When will the (0.150.0  or  0.200.0 ) version be released ?

**Comment by tlento** [comment]
It rolled to PyPi last Thursday! https://github.com/dbt-labs/metricflow/releases/tag/v0.200.0
