### ISSUE TITLE
[Feature] Replace Uses of Patches / Mocks  In test_cli.py

### ISSUE THREAD

**Issue by plypaul** [dbt-labs/metricflow#564]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Some of the tests in `test_cli.py` use patched mock objects. These objects make it more difficult to refactor and trace usage in the IDE, so it would be helpful to migrate them to actual objects. Based on a cursory inspection of the tests in that file, there are now utility methods that should make the migration straightforward.

**Comment by tlento** [comment]
YES!

**Comment by WilliamDee** [comment]
https://github.com/dbt-labs/metricflow/pull/605 this removed the Mocks
