### ISSUE TITLE
Relax version pins on production dependencies

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#707]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

MetricFlow still has a number of internal dependencies with version pins to specific versions. In particular:

```
  "MarkupSafe==2.0.1",
  "graphviz==0.18.2",
  "jsonschema==3.2.0",
  "more-itertools==8.10.0",
  "python-dateutil==2.8.2",
  "rapidfuzz==3.0.0",
```

These should be relaxed as far as we are able. jsonschema, more-itertools, python-dateutil, and rapidfuzz are probably the most critical production dependencies on that list.

**Comment by davidmathers** [comment]
The linked pull request won't close this issue

```werkzeug 2.2.3 requires MarkupSafe>=2.1.1, but you have markupsafe 2.0.1 which is incompatible.```

MarkupSafe 2.1.1 was released March 15, 2022

MarkupSafe 2.0.1 was released May 18, 2021

Please don't pin dependencies that are 2.5 years old
