### ISSUE TITLE
[SL-1291] [Feature] Support Window Functions for cumulative metrics

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#736]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

MetricFlow has some primitive support for window functions, but expanding this could allow for a lot of improvements in our query performance.

As an example, a cumulative metric maintaining a running total across all history currently renders like this:

```
SELECT
  subq_869.date_day AS metric_time__day
  , SUM(order_item_src_2.product_price) AS cumulative_revenue
FROM ANALYTICS.metricflow_time_spine subq_869
INNER JOIN
  RAW.ANALYTICS.order_items order_item_src_2
ON
  (order_item_src_2.ordered_at <= subq_869.date_day)
GROUP BY
  subq_869.date_day
ORDER BY metric_time__day DESC
```

This does an expansive join against a time spine for every row of input, which means scanning and re-scanning the previous dates. However, for any SUM/MIN/MAX we could use a window function instead of a join to do the cumulative aggregation, which we should be able to do in linear time.

<sub>[SL-1291](https://linear.app/dbt-labs/issue/SL-1291/[feature]-support-window-functions-for-cumulative-metrics)</sub>

**Comment by Jstein77** [comment]
I think window functions as an aggregation type would be useful outside of cumulative metrics. One example is using window functions to calculate cohort size for cohort analysis ([community slack reference here)](https://getdbt.slack.com/archives/C02CCBBBR1D/p1695829317557339). When doing a cohort analysis, you need to calculate the cohort start date and the cohort size. Below is an example of transforming a raw events table to get the data ready for cohort analysis.  
<img width="707" alt="Screenshot 2023-09-27 at 10 29 32 AM" src="https://github.com/dbt-labs/metricflow/assets/26796796/0145f5cc-473a-4b17-9361-6e56d7daac12">

The SQL would look something like the following: 
`SELECT
ordered_at as date_time,
first_purchase_month,
count(distinct buyer_id) as cohort_ordering ,
count(distinct buery_id) over (partition by first_purchase_month) as cohort_size,
cohort_ordering/cohort_size
FROM
cohort_table
GROUP BY
1,2`



Currently, `cohort_size` needs to be pre-calculated at the modeling layer. If we supported window functions then we could natively define this measure in metricflow.

**Comment by tlento** [comment]
@Jstein77 agreed. I think we'd want to implement them as a separate rendering construct, accessible to any aggregation type that might benefit from them.

**Comment by josepfranquetf** [comment]
Totally agree. Additionally, it would be great if the partition by statement were dynamic in terms of the demanded dimensions in the `mf query` request. 

**For monthly cohorts:**

`mf query --metrics pct_cohorts_with_orders --group-by date_time__month,first_purchase_month__month`  

With this corresponding window function:

`count(distinct buyer_id) over (partition by first_purchase_month__month)`

**For yearly cohorts:**

`mf query --metrics pct_cohorts_with_orders --group-by date_time__year,first_purchase_month__year`  

With this corresponding function:

`count(distinct buyer_id) over (partition by first_purchase_month__year)`

Do you see the dynamism in the expression of the metric/measure defined as a window function @tlento and @Jstein77?

**Comment by tlento** [comment]
@josepfranquetf initially, at least for conversion metrics, we would only support specifying the partition in the metric definition via the window/granularity specification. So you'd have to define both a `pct_cohort_with_orders_monthly` and a `pct_cohort_with_orders_yearly` metric, and query them as separate entities.

We are discussing ways to allow for dynamic window specifications, as we will need them for other contexts as well (e.g., conversion/retention metric queries that are keyed off of an arbitrary set of events, like a particular ad campaign, such that the window has to be bound to a moment rather than an offset). That won't happen for some time, though, as it's fairly tricky to get an interface that makes it clear to people what's happening under the hood and what they should expect from the metric query.
