### ISSUE TITLE
[Bug] Meta is Missing in semantic_manifest.json

### ISSUE THREAD

**Issue by HoseinBahmany** [dbt-labs/metricflow#739]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Not sure whether this is a bug in the MetricFlow or dbt-core. Since this happens in the context of metadata for `metric` objects I thought it might be better to report it here.

I have two observations regarding the `meta` attribute:
- Adding `meta` to a `semantic_model` would cause the following error:
  ```
  Invalid semantic_models config given in FilePath(..., 'meta': {'key1': 'value1'}} - at path []: Additional properties are not allowed ('meta' was unexpected)
  ```
  It seems the `meta` is not allowed on `semantic_models`
- Adding `meta` to metrics would not cause any errors. But it would not appear in the `semantic_manifest.json` as well:
```
# metric definition in yml file
  - name: revenue
    description: Sum of the product revenue for each order item. Excludes tax.
    type: simple
    label: Revenue
    type_params:
      measure: revenue
    meta:
      owner: Jake

# relavent part of semantic_manifest.json
{
      "name": "revenue",
      "agg": "sum",
      "description": "The revenue generated for each order item. Revenue is calculated as a sum of revenue associated with each product in an order.",
      "create_metric": false,
      "expr": "product_price",
      "agg_params": null,
      "metadata": null,
      "non_additive_dimension": null,
      "agg_time_dimension": null
}
```

### Expected Behavior

Based on the [discussion](https://github.com/dbt-labs/dbt-core/discussions/7456) it seems that `meta` should be supported on all dbt objects including the `semantic_models` and `metrics`

### Steps To Reproduce

Simply add `meta` attribute to a `semantic_model` or a `metric`. I tested this on the `jaffle_shop` sample repo.

### Environment

```markdown
- OS: Window 10
- Python: 3.10
- dbt: 1.6.1
- metricflow: 0.201.0
```

### Which database are you using?

postgres

**Comment by QMalcolm** [comment]
@HoseinBahmany I wanted to let you know that we are now tracking this in a [dbt-core issue](https://github.com/dbt-labs/dbt-core/issues/8511). It's worth noting that it'll be specifiable, but likely will still not appear in the `semantic_manifest.json`. It will appear in the `manifest.json` though. Is there a specific use case you have that requires it to be in the `semantic_manifest.json`, or was that more so a debugging step?

**Comment by HoseinBahmany** [comment]
Thank you @QMalcolm for the follow-up. I was trying to specify some metadata in my metric, like example usages, etc that would be helpful in my downstream visualization tools. I'm doing those in the `description` at the moment but it would make more sense to specify those in the metadata so my downstream tool can easily extract them. 

In my downstream tool, I was parsing the `semantic_manifest.json` and thought I would find the metadata in there.

**Comment by Jstein77** [comment]
This should be resolved with https://github.com/dbt-labs/dbt-core/issues/8511

**Comment by alenaomal** [comment]
Hi all! Really appreciate fixes related to this bug, thanks! But would like to return to the point that based on the https://github.com/dbt-labs/dbt-core/discussions/7456 meta should be supported in **all** dbt objects.  
Currently it is supported in metrics, using 'meta', and in semantic_models, using 'config/meta'.  
For my use cases it will be really helpful to have meta in entities, measures and dimensions as well.   
Now i get same error for 'meta' and 'config/meta' properties.  
`- at path ['measures'][0]: Additional properties are not allowed ('meta' was unexpected)  
- at path ['measures'][0]: Additional properties are not allowed ('config' was unexpected)`
