### ISSUE TITLE
[Feature] Additional version of --explain with refs intact

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/metricflow#749]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As pointed out in [this thread](https://getdbt.slack.com/archives/C02CCBBBR1D/p1691074012027309), currently the only replacement for metrics.calculate is to
- use `--explain` to return the compiled SQL
- copy-paste the returned SQL code into a model

Unfortunately the SQL code is 'fully compiled', meaning the ref('model_name') has been replaced with schema_name.table_name. To keep our data lineage graphs, we need to add a third step of manually reviewing the code to replace all the hardcoded table references with the dbt refs to other models.

The last step could be avoided if there was a special way to query the metric, for example `--explain --keeprefs` that would keep the refs but compile the rest of the code.

### Describe alternatives you've considered

Manual review of the SQL code. It is an option, but very error prone and repetitive. 

### Who will this benefit?

Anyone who currently uses metrics.calculate and needs to migrate to Metric Flow. 

### Are you interested in contributing this feature?

Sure, although I doubt I can help.

**Comment by Jstein77** [comment]
Thanks for adding this @siljamardla! I think there are some problems with this approach. `--explain` returns the compiled SQL, it's a similar command to `dbt compile`. We're actually going to rename `--explain` to `compile` to align these two commands. The purpose of this command is to show the compiled SQL that's executed against your warehouse. It feels weird to add jinja into the mix.

On the technical side, MetricFlow isn't aware of the dependency graph for metrics, so there isn't a great way to inject the `ref()` macro into the compiled SQL, even if this is something we did want to do.

**Comment by Jstein77** [comment]
Closing this issue for now. This isn't something we're going to work on right now.
