### ISSUE TITLE
[SL-1286] [Feature] Support granularity for cumulative metrics

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#791]
### **Problem Overview** 🗺️

I would like to be able to request cumulative metrics by granularities other than day, similar to the granularity options for other metric types. For example, if I request a cumulative metric by monty I would expect to see a row for each month, with the cumulative metric value for that given month.

Supporting the full range of granularity options simplifies the process of creating cumulative metrics at different grains. If I want to create a cumulative metric at another grain today, I need to create an entirely different metric definition. This adds unnecessary configuration to my dbt project.

### **Proposed Solution** 🔧

I should be able to request a different granularity for cumulative metrics at query time, for example `dbt sl query --metrics orders_last_7_days --group-by metric_time__week` should show me cumulative revenue for each week. Since cumulative metrics are not additive over time, we need to know how to aggregate the metric value when someone requests the cumulative metric be rolled up to a coarser grain. We will take the minimum value or maximum value of the cumulative metric for the requested granularity window. Users will be able to configure the min or max window choice with min being the default. (Figure 1)

![Group 1 (1)](https://github.com/dbt-labs/metricflow/assets/26796796/d683bdf3-68ea-42d8-b0f0-923361e1f48a)
59-88e3-c3fa27c8e63f/Group_1_(1).png)

*Figure 1: The first table shows orders_last_7_days by day. The second table shows the weekly granularity. We take the first value of each we when the minimum window choice is chosen.*

### Features 🔩

1. Users can configure the window_choice as a type parameter on cumulative metrics. This tells MetricFlow how to roll up the cumulative metric to another granularity. If no window is specified, we default to min.
    
    *Example configs:* 
    
    *Cumulative metric w/no window. Window choice is min.*
    
    ```yaml
      - name: cumulative_revenue
        description: The cumulative revenue for all orders.
        label: Cumulative Revenue (All Time)
        type: cumulative
        type_params:
          measure: revenue
          window_choice: min #Optional. defaults to min. Accepted values are min|max
    ```
    
    - This compiles into the following SQL
        
        ```sql
        --mf query --metrics cumulative_revenue --group-by metric_time__wwek
        WITH staging AS (
            SELECT
                subq_3.date_day AS metric_time__day,
                DATE_TRUNC('week', subq_3.date_day) AS metric_time__week,
                SUM(subq_1.revenue) AS cumulative_revenue
            FROM
                dbt_sl_test.metricflow_time_spine subq_3
            INNER JOIN (
                SELECT
                    DATE_TRUNC('day', CAST(ordered_at AS DATETIME)) AS metric_time__day,
                    product_price AS revenue
                FROM
                    ANALYTICS.dbt_jstein.order_items order_item_src_10000
            ) subq_1 ON (subq_1.metric_time__day <= subq_3.date_day)
            WHERE
                subq_3.date_day BETWEEN '2016-01-01' AND '2017-12-31'
            GROUP BY
                subq_3.date_day
            ORDER BY
                1
        )
        
        SELECT
            *
        FROM
            (
                SELECT
                    metric_time__week,
                    FIRST_VALUE(cumulative_revenue) OVER (PARTITION BY DATE_TRUNC('week', metric_time__day) ORDER BY metric_time__day) AS cumulative_revenue
                FROM
                    staging
            )
        GROUP BY
            metric_time__week,
            cumulative_revenue
        ORDER BY
            metric_time__week
        ```
        
    
    *Cumulative metric w/no window. Window choice is max.*
    
    ```sql
      - name: cumulative_revenue
        description: The cumulative revenue for all orders.
        label: Cumulative Revenue (All Time)
        type: cumulative
        type_params:
          measure: revenue
          window_choice: max #or max
    ```
    
    - This compiles into the following SQL
        
        ```sql
        WITH staging AS (
            SELECT
                subq_3.date_day AS metric_time__day,
                DATE_TRUNC('week', subq_3.date_day) AS metric_time__week,
                SUM(subq_1.revenue) AS cumulative_revenue
            FROM
                dbt_sl_test.metricflow_time_spine subq_3
            INNER JOIN (
                SELECT
                    DATE_TRUNC('day', CAST(ordered_at AS DATETIME)) AS metric_time__day,
                    product_price AS revenue
                FROM
                    ANALYTICS.dbt_jstein.order_items order_item_src_10000
            ) subq_1 ON (subq_1.metric_time__day <= subq_3.date_day)
            WHERE
                subq_3.date_day BETWEEN '2016-01-01' AND '2017-12-31'
            GROUP BY
                subq_3.date_day
            ORDER BY
                1
        )
        
        SELECT
            *
        FROM
            (
                SELECT
                    metric_time__week,
                    FIRST_VALUE(cumulative_revenue) OVER (PARTITION BY DATE_TRUNC('week', metric_time__day) ORDER BY metric_time__day desc) AS cumulative_revenue
                FROM
                    staging
            )
        GROUP BY
            metric_time__week,
            cumulative_revenue
        ORDER BY
            metric_time__week
        ```
        
    
    *Cumulative metric w/ 7 day window:*
    
    ```sql
      - name: orders_last_7_days
        description: Count of orders.
        label: orders last 7 days
        type: cumulative
        type_params:
          measure: order_count
          window: 7 days
          window_choice: min #or max
    ```
    
    - This compiled into the following SQL
        
        ```sql
        --dbt sl query --metrics orders_last_7_days --group-by metric_time__week
        with staging as (
        SELECT
          subq_3.date_day AS metric_time__day
          , DATE_TRUNC('week', subq_3.date_day) AS metric_time__week
          , SUM(subq_1.order_count) AS orders_last_7_days
        FROM dbt_sl_test.metricflow_time_spine subq_3
        INNER JOIN (
          SELECT
            DATE_TRUNC('day', ordered_at) AS metric_time__day
            , 1 AS order_count
          FROM ANALYTICS.dbt_jstein.orders orders_src_10000
        ) subq_1
        ON
          (
            subq_1.metric_time__day <= subq_3.date_day
          ) AND (
            subq_1.metric_time__day > DATEADD(day, -7, subq_3.date_day)
          )
        WHERE
                subq_3.date_day BETWEEN '2016-01-01' AND '2017-12-31'
        GROUP BY
          subq_3.date_day
        )
        
        SELECT
            *
        FROM
            (
                SELECT
                    metric_time__week,
                    FIRST_VALUE(orders_last_7_days) OVER (PARTITION BY DATE_TRUNC('week', metric_time__day) ORDER BY metric_time__day) AS cumulative_revenue
                FROM
                    staging
            )
        GROUP BY
            metric_time__week,
            cumulative_revenue
        ORDER BY
            1
        ```
        

### Requirements 🦺

- Update cumulative metric type params to include `window_choice: min|max`
- Update dataflow plan to determine the min or max value for the granularity window

### Questions 🤔

- Should we rename `window` —> `lookback_window` ?
    - Pros:
        - More explicit about what the window does
        - If we introduce `window_choice` as an optional param, it becomes more imporant to differentiate window
    - Cons:
        - Breaking change!
<sub>From [SyncLinear.com](https://synclinear.com) | [SL-1286](https://linear.app/dbt-labs/issue/SL-1286/[feature]-support-granularity-for-cumulative-metrics)</sub>

**Comment by courtneyholcomb** [comment]
This is its own milestone now, so canceling the task
