### ISSUE TITLE
[Bug] date_part/extract returns different values for DAY OF WEEK depending on engine

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#792]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The current implementation of the query-time date_part/extract SQL rendering returns whatever the underlying engine returns. Our assumption was that the engines would follow the same day of week standard they use for date_trunc. Bless our naive little hearts..... this is obviously not how the world works.

Currently, all of our engines (save Snowflake, which is user-configurable) use the ISO standard of week_start = Monday for granularity adjustments. As far as I can tell, the date_part returns:

1. Databricks, DuckDB, Postgres, Redshift: 0-6, where 0 is Sunday and 6 is Saturday
2. BigQuery: ISO standard 1-7, Monday - Sunday, because we overrode this
3. Snowflake: consistent with date_trunc, ISO standard 1-7, Monday - Sunday

### Expected Behavior

MetricFlow should return the same value range and day of week mappings regardless of engine. Whether that should be the SAME as the granularity adjustment (ISO week starts on Monday) or DIFFERENT (every engine except Snowflake defaults to 0-6, Sunday-Saturday) is a separate question, but "we use ISO standard week starts" has a certain appeal to it.

### Steps To Reproduce

Query date_part on different engines and see what happens.

### Environment

```markdown
- OS:
- Python:
- dbt:
- metricflow:
```

**Comment by aiguofer** [comment]
Turns out Snowflake is not currently returning ISO standard, but it does support it through `dayofweekiso`: https://docs.snowflake.com/en/sql-reference/functions-date-time#label-supported-date-time-parts
