### ISSUE TITLE
[Bug] Can't run metricflow commands "can't find file"

### ISSUE THREAD

**Issue by Gonzalo933** [dbt-labs/metricflow#807]
UPDATE: See comment

### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I try to run a metricflow command like `mf tutorial` I get an error

`$ mf tutorial`

> This is METAFONT, Version 2.71828182 (TeX Live 2022) (preloaded base=mf)
> 
> kpathsea: Running mktexmf tutorial
> ! I can't find file `tutorial'.
> <*> tutorial
>             
> Please type another input file name: 
> ! Emergency stop.
> <*> tutorial
>             
> Transcript written on mfput.log.

Same problem with `mf validate-configs` or `mf query --metrics metric_name --group-by dimension_column`

### Expected Behavior

I expect the command to run without errors.

### Steps To Reproduce

1. Create empty python 3.9 conda environment.
2. Install dbt and metric flow `pip install dbt-snowflake` and `pip install dbt-metricflow[snowflake]`
3. Run `mf tutorial`

### Relevant log output

```shell
mfput.log doesn't have useful information


This is METAFONT, Version 2.71828182 (preloaded base=mf 2022.12.15)  12 OCT 2023 14:51
**validate-configs

! Emergency stop.
<*> validate-configs
                    
End of file on the terminal!
```
```


### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Python: Python 3.9.18
- dbt: 1.6.6
- metricflow: Metafont 2.71828182 (TeX Live 2022) kpathsea version 6.3.4
```

### Which database are you using?

snowflake

### Additional Context

I think this error may be related to my latex installation. But latex is not listed as a dependency for mf

**Comment by Gonzalo933** [comment]
Turns out that the command `mf` points to a latex package called metafont.
```
$ which mf
/usr/local/texlive/2022/bin/x86_64-linux/mf
```

I guess we can close the issue but there is a chance that people may run into this issue

**Comment by Jstein77** [comment]
Thanks Gonzalo! Good to know. We can add this to docs as a common gotcha.
