### ISSUE TITLE
[SL-1247] [Bug] Invalid dimension suggestions are confusingly broken

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#822]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We are in an uncanny valley where the old dunder-everywhere reference syntax lives in a bunch of our user guidance but does not actually work in the interface itself. To make matters worse, that syntax still probably does work in some cases but not others.

This issue is about the specific instance of the UnableToSatisfyQueryError that recommends dimensions and so forth. If someone requests `user__country` and `invite_event__created_at` we will suggest things like `event__user__country` and `invite_event__created_at__day`.

These will not work. The user instead has do `Dimension('user__country', ['event'])` and `TimeDimension('invite_event__created_at', 'day')` or similar.

We should update the error message to indicate how to copy/paste things to get the response correct. Ideally we'd be able to recognize that there is a name match and ask "did you mean....." as well.

### Expected Behavior

Users should be able to copy/paste suggested dimensions out of the list and have their queries work.

### Steps To Reproduce

Run a query with an ambiguous dimension name and read the error message.

### Environment

```markdown
- OS:
- Python:
- dbt:
- metricflow:
```

<sub>[SL-1247](https://linear.app/dbt-labs/issue/SL-1247/[bug]-invalid-dimension-suggestions-are-confusingly-broken)</sub>

**Comment by marcodamore** [comment]
Yo @jordan.stein this is marked as urgent but hasn't been touched in a while - what should we do with it?

**Comment by tlento** [comment]
I think @plypaul fixed this with the refactor on group by resolution, but I haven't verified it myself.
