### ISSUE TITLE
[Bug] `mf` should return a nonzero error code when `mf validate-configs` command returns errors

### ISSUE THREAD

**Issue by waligob** [dbt-labs/metricflow#867]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Initially noted in [this dbt Slack thread](https://getdbt.slack.com/archives/C02CCBBBR1D/p1699642411535029):

I’m running an `mf` command that errors with an exception, so I would expect it to return a non-zero return code. Instead, I get a return code of `0` .

### Expected Behavior

mf returns an error code of `0` when mf commands do not complete cleanly. 

### Steps To Reproduce

Ensure that you do not have a `target/semantic_manifest.json` file in your root project directory, and run:

```
$ mf validate-configs --show-all --verbose-issues --skip-dw
```

### Relevant log output

```shell
$ mf validate-configs --show-all --verbose-issues --skip-dw
✖ Exception found when parsing manifest from dbt project (An error occurred when attempting to build the semantic model
Unable to find /workspaces/inquirer-dbt/target/semantic_manifest.json
Please ensure that you are running `mf` in the root directory of a dbt project and that the semantic_manifest JSON exists. If this is your first time running `mf`, run `dbt parse` to generate the semantic_manifest JSON.)
$ echo $?
0
```
```


### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Python: 3.9.17
- dbt: 1.6.9
- metricflow: 0.202.0
```

### Which database are you using?

bigquery

**Comment by Jstein77** [comment]
@waligob  Thanks for flagging!

**Comment by epapineau** [comment]
+1 - we're trying to leverage `mf validate-configs` in a CI check and this would make that work easier
