### ISSUE TITLE
[SL-1346] [Bug] Filters specified on nested derived metrics are not properly applied

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#920]
Under certain circumstances, filters aren’t applied in nested derived metrics. https://getdbt.slack.com/archives/C02CCBBBR1D/p1701795017142279

The issue here is that we do not render filters specified on a derived metric definition that has other filtered derived metrics defined as its inputs. See https://github.com/dbt-labs/metricflow/pull/919 for a test illustrating the rendering problem.

<sub>[SL-1346](https://linear.app/dbt-labs/issue/SL-1346/filters-specified-on-nested-derived-metrics-are-not-properly-applied)</sub>

**Comment by plypaul** [comment]
It seems like this was fixed as a side effect of the dataflow plan updates in the group-by-item resolution PR. Mind regenerating your snapshots?

**Comment by marcodamore** [comment]
Pinged @tomkit.lento to double check whether this is fixed

**Comment by tlento** [comment]
Yes, I think this is fixed! I'll put up a PR with some added test cases and include a changelog entry indicating that this was fixed with 0.204.0

**Comment by marcodamore** [comment]
Sweeeet ty

**Comment by tlento** [comment]
Tests merged so this is doubly-done!

**Comment by marcodamore** [comment]
Yeehaw
