### ISSUE TITLE
[SL-1528] [Feature] Support add "having" parameter

### ISSUE THREAD

**Issue by UncleFB** [dbt-labs/metricflow#965]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Can we support passing in the having parameter when querying?

<sub>[SL-1528](https://linear.app/dbt-labs/issue/SL-1528/[feature]-support-add-having-parameter)</sub>

**Comment by kingduxia** [comment]
We are dealing with some cases where we need to filter data based on specific criteria, such as when a measure is greater than a certain value (xx) or less than another value (yy). We are looking for guidance on how to define a semantic model in MetricFlow to handle these types of scenarios.

**Comment by Jstein77** [comment]
@kingduxia We've heard that exact use case come up several times. We have work planned to enable this since it's really common.

**Comment by Jstein77** [comment]
@UncleFB I wrote up some more details on how we would support this here https://github.com/dbt-labs/metricflow/issues/1018. Would love your feedback!
