### ISSUE TITLE
[SL-1529] [Bug] Poetry can't resolve dependencies when adding the package

### ISSUE THREAD

**Issue by sacses** [dbt-labs/metricflow#972]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After executing command `poetry add "dbt-metricflow[redshift]"`, poetry starts to attempt to resolve dependencies without ever finalising.

### Expected Behavior

Poetry can resolve dependencies and install `"dbt-metricflow[redshift]"`

### Steps To Reproduce

1. `poetry init`
2. `poetry add dbt-core=1.7.2`
3. Limit python supported dependency to `">3.9,<3.12"`

Resulting dependencies in `pyproject.toml`:
```
[tool.poetry.dependencies]
python = ">3.9,<3.12"
dbt-core = "1.7.2"
dbt-redshift = "1.7.1"
```

### Relevant log output

```shell
<user>@<device> test_dbt_core % poetry add "dbt-metricflow[redshift]" 
Using version ^0.4.0 for dbt-metricflow

Updating dependencies
Resolving dependencies... 
```

### Environment

```markdown
- OS: MacOC Monterrey 12.7.1
- Python: 3.9.11
- dbt: 1.7.2
- metricflow: None
- poetry: 1.1.15
```

### Which database are you using?

redshift

<sub>[SL-1529](https://linear.app/dbt-labs/issue/SL-1529/[bug]-poetry-cant-resolve-dependencies-when-adding-the-package)</sub>

**Comment by Jstein77** [comment]
@sacses Thanks for flagging, this should work 🤔. Can you try just running `poetry add metricflow` and see if that works?

**Comment by sacses** [comment]
> Can you try just running `poetry add metricflow` and see if that works?

Same dependency infinite loop

```
% poetry add metricflow
Using version ^0.204.0 for metricflow

Updating dependencies
Resolving dependencies... (566.8s)
```

**Comment by Jstein77** [comment]
@WilliamDee @tlento hmm can you take a look at this one?

**Comment by WilliamDee** [comment]
Hey @sacses!

I just took a little dive into this and came to some conclusions. Seems like just running `poetry add "dbt-metricflow[redshift]"` makes poetry pin at the latest `0.5.0` version which isn't compatible with your specified `dbt-core` version, I'm using poetry 1.7.x which seems to have resolved and outputted that conflict.
<img width="950" alt="Screenshot 2024-01-19 at 2 13 11 PM" src="https://github.com/dbt-labs/metricflow/assets/33618746/d1993fc3-a8e7-4276-a506-39c13d2675e2">

 So in order for me to get it working, I had to run `poetry add "dbt-metricflow[redshift]==0.4.0"` to pin it to the compatible version. However, the poetry version you're using is quite old, and seems to have [consistent feedback about it being slow](https://github.com/python-poetry/poetry/issues/2094#issuecomment-1226084557). When I tried running `poetry add "dbt-metricflow[redshift]==0.4.0"` in `poetry==1.1.x`, it still had the same issue where it hung at resolving dependencies indefinitely. I would recommend, if possible, to try upgrading to a later versions of poetry, it seems like even `1.2.0` which is 1 minor bump from yours has significant boost in performance. Let me know if this helps!

**Comment by sacses** [comment]
Thanks a lot @WilliamDee and apologies for the late response on my end. \
I hereby confirm that adding the dependency `"dbt-metricflow[redshift]==0.4.0"` via the current stable version `poetry: 1.7.1`, after uninstalling `poetry: 1.1.15` following the instructions in [this GH issue](https://github.com/python-poetry/poetry/issues/2245#issuecomment-1623914081) and [reinstalling poetry](https://python-poetry.org/docs/master#installing-with-the-official-installer) worked like a charm 👌
